sudo: required
dist: trusty
language: node_js
node_js:
  - '10'

cache:
  directories:
    - "node_modules"

install:
  - npm install -g truffle
  - npm install ganache-cli
  - npm install

script:
  - ganache-cli -p 7545 > /dev/null &
  - sleep 5
  - truffle migrate --reset
  - truffle test
